apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgresql
        securityContext:
          runAsUser: 0
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_USER
          value: db
        - name: POSTGRES_PASSWORD
          value: db
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: gpt
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30532

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: gpt
spec:
  volumeName: postgresql-gpt-pv
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 6Gi

